### ISSUE TITLE
merge_variants not including all variants

### ISSUE THREAD

**Issue by gregmcinnes** [ctsa/gvcftools#4]
Hi Chris,

I'm trying to merge the variants the BRCA1 from platinum genome gVCF files into a single merged VCF using merge_variants.  After running the command I found that many of the variants from the individual gVCF files are not included in the resulting merged file.  Do you know of any reason why this might be happening?  It seems that, on average, the sites that are excluded are generally lower quality calls.  However, there are sites that are included that have overall worse quality than some of the excluded sites.  Let me know if you need more information.

```
merge_variants --murdock --region chr17:41196312-41277500 --ref /srv/gs1/projects/scg/Genomes/H_sapiens/hg19/chr17.fa --input NA12877.brca1.expanded.vcf.gz --input NA12878.brca1.expanded.vcf.gz --input NA12879.brca1.expanded.vcf.gz --input NA12880.brca1.expanded.vcf.gz --input NA12881.brca1.expanded.vcf.gz --input NA12882.brca1.expanded.vcf.gz --input NA12883.brca1.expanded.vcf.gz --input NA12884.brca1.expanded.vcf.gz --input NA12885.brca1.expanded.vcf.gz --input NA12886.brca1.expanded.vcf.gz --input NA12887.brca1.expanded.vcf.gz --input NA12888.brca1.expanded.vcf.gz --input NA12889.brca1.expanded.vcf.gz --input NA12890.brca1.expanded.vcf.gz --input NA12891.brca1.expanded.vcf.gz --input NA12892.brca1.expanded.vcf.gz --input NA12893.brca1.expanded.vcf.gz > platinum_genomes_brca1_merged.vcf
```

Greg

**Comment by VelNZ** [comment]
I can confirm that gvcftools will not print a variant that is LowGQX quality in all samples. It seems to require at least one to be PASS. This is fine but it would be helpful if it was documented somewhere! I had to create a test case with 3 samples to confirm it.
